using Microsoft.EntityFrameworkCore;
using MovieCollection.Data.Entities;
using System;

namespace MovieCollection.Data.DataContexts
{
    public class MovieDbContext : DbContext
    {
        public MovieDbContext(DbContextOptions<MovieDbContext> options)
            : base(options)
        {

        }

        public DbSet<Movie> Movies { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movie>().HasData(
                new Movie { ID = 429351, Title = "12 Strong", ReleaseDate = new DateTime(2018, 1, 16), Genre = "Drama" },
                new Movie { ID = 64688, Title = "21 Jump Street", ReleaseDate = new DateTime(2012, 3, 12), Genre = "Action" },
                new Movie { ID = 53182, Title = "300: Rise of an Empire", ReleaseDate = new DateTime(2014, 3, 5), Genre = "Drama" },
                new Movie { ID = 403119, Title = "47 Meters Down", ReleaseDate = new DateTime(2017, 5, 25), Genre = "Adventure" },
                new Movie { ID = 64686, Title = "47 Ronin", ReleaseDate = new DateTime(2013, 12, 6), Genre = "Adventure" },
                new Movie { ID = 12244, Title = "9", ReleaseDate = new DateTime(2009, 8, 19), Genre = "Adventure" },
                new Movie { ID = 17979, Title = "A Christmas Carol", ReleaseDate = new DateTime(2009, 11, 4), Genre = "Animation" },
                new Movie { ID = 340837, Title = "A Cure for Wellness", ReleaseDate = new DateTime(2017, 2, 15), Genre = "Horror" },
                new Movie { ID = 428449, Title = "A Ghost Story", ReleaseDate = new DateTime(2017, 7, 7), Genre = "Fantasy" },
                new Movie { ID = 47964, Title = "A Good Day to Die Hard", ReleaseDate = new DateTime(2013, 2, 6), Genre = "Action" },
                new Movie { ID = 447332, Title = "A Quiet Place", ReleaseDate = new DateTime(2018, 4, 3), Genre = "Drama" },
                new Movie { ID = 169917, Title = "A Walk Among the Tombstones", ReleaseDate = new DateTime(2014, 9, 18), Genre = "Drama" },
                new Movie { ID = 10229, Title = "A Walk to Remember", ReleaseDate = new DateTime(2002, 1, 25), Genre = "Drama" },
                new Movie { ID = 407451, Title = "A Wrinkle in Time", ReleaseDate = new DateTime(2018, 3, 8), Genre = "Adventure" },
                new Movie { ID = 122906, Title = "About Time", ReleaseDate = new DateTime(2013, 8, 16), Genre = "Drama" },
                new Movie { ID = 72331, Title = "Abraham Lincoln: Vampire Hunter", ReleaseDate = new DateTime(2012, 6, 20), Genre = "Fantasy" },
                new Movie { ID = 445954, Title = "Acts of Vengeance", ReleaseDate = new DateTime(2017, 10, 27), Genre = "Drama" },
                new Movie { ID = 79931, Title = "Adele: Live at the Royal Albert Hall", ReleaseDate = new DateTime(2011, 11, 27), Genre = "Music" },
                new Movie { ID = 82700, Title = "After Earth", ReleaseDate = new DateTime(2013, 5, 30), Genre = "Adventure" },
                new Movie { ID = 9772, Title = "Air Force One", ReleaseDate = new DateTime(1997, 7, 25), Genre = "Action" },
                new Movie { ID = 12155, Title = "Alice in Wonderland", ReleaseDate = new DateTime(2010, 3, 3), Genre = "Adventure" },
                new Movie { ID = 402529, Title = "All Eyez on Me", ReleaseDate = new DateTime(2017, 6, 12), Genre = "Drama" },
                new Movie { ID = 415842, Title = "American Assassin", ReleaseDate = new DateTime(2017, 9, 14), Genre = "Action" },
                new Movie { ID = 190859, Title = "American Sniper", ReleaseDate = new DateTime(2014, 12, 11), Genre = "Action" },
                new Movie { ID = 250546, Title = "Annabelle", ReleaseDate = new DateTime(2014, 10, 2), Genre = "Horror" },
                new Movie { ID = 102899, Title = "Ant-Man", ReleaseDate = new DateTime(2015, 7, 14), Genre = "Adventure" },
                new Movie { ID = 68734, Title = "Argo", ReleaseDate = new DateTime(2012, 10, 11), Genre = "Drama" },
                new Movie { ID = 95, Title = "Armageddon", ReleaseDate = new DateTime(1998, 7, 1), Genre = "Adventure" },
                new Movie { ID = 329865, Title = "Arrival", ReleaseDate = new DateTime(2016, 11, 10), Genre = "Drama" },
                new Movie { ID = 16577, Title = "Astro Boy", ReleaseDate = new DateTime(2009, 10, 15), Genre = "Animation" },
                new Movie { ID = 341013, Title = "Atomic Blonde", ReleaseDate = new DateTime(2017, 7, 26), Genre = "Action" },
                new Movie { ID = 242643, Title = "Batman: Assault on Arkham", ReleaseDate = new DateTime(2014, 8, 12), Genre = "Animation" },
                new Movie { ID = 366924, Title = "Batman: Bad Blood", ReleaseDate = new DateTime(2016, 3, 22), Genre = "Animation" },
                new Movie { ID = 471474, Title = "Batman: Gotham by Gaslight", ReleaseDate = new DateTime(2018, 1, 12), Genre = "Animation" },
                new Movie { ID = 411736, Title = "Batman: Return of the Caped Crusaders", ReleaseDate = new DateTime(2016, 10, 8), Genre = "Animation" },
                new Movie { ID = 272, Title = "Batman Begins", ReleaseDate = new DateTime(2005, 6, 10), Genre = "Drama" },
                new Movie { ID = 485942, Title = "Batman Ninja", ReleaseDate = new DateTime(2018, 4, 24), Genre = "Animation" },
                new Movie { ID = 44833, Title = "Battleship", ReleaseDate = new DateTime(2012, 4, 11), Genre = "Adventure" },
                new Movie { ID = 339846, Title = "Baywatch", ReleaseDate = new DateTime(2017, 5, 12), Genre = "Action" },
                new Movie { ID = 321612, Title = "Beauty and the Beast", ReleaseDate = new DateTime(2017, 3, 16), Genre = "Fantasy" },
                new Movie { ID = 25979, Title = "Bee Gees: One Night Only", ReleaseDate = new DateTime(1997, 12, 31), Genre = "Music" },
                new Movie { ID = 399248, Title = "Beirut", ReleaseDate = new DateTime(2018, 4, 11), Genre = "Action" },
                new Movie { ID = 177572, Title = "Big Hero 6", ReleaseDate = new DateTime(2014, 10, 24), Genre = "Adventure" },
                new Movie { ID = 284054, Title = "Black Panther", ReleaseDate = new DateTime(2018, 2, 13), Genre = "Adventure" },
                new Movie { ID = 426284, Title = "Blade of the Immortal", ReleaseDate = new DateTime(2017, 4, 29), Genre = "Drama" },
                new Movie { ID = 335984, Title = "Blade Runner 2049", ReleaseDate = new DateTime(2017, 10, 4), Genre = "Thriller" },
                new Movie { ID = 13053, Title = "Bolt", ReleaseDate = new DateTime(2008, 11, 21), Genre = "Adventure" },
                new Movie { ID = 271110, Title = "Captain America: Civil War", ReleaseDate = new DateTime(2016, 4, 27), Genre = "Adventure" },
                new Movie { ID = 1771, Title = "Captain America: The First Avenger", ReleaseDate = new DateTime(2011, 7, 22), Genre = "Adventure" },
                new Movie { ID = 109424, Title = "Captain Phillips", ReleaseDate = new DateTime(2013, 10, 10), Genre = "Drama" },
                new Movie { ID = 49013, Title = "Cars 2", ReleaseDate = new DateTime(2011, 6, 11), Genre = "Adventure" },
                new Movie { ID = 920, Title = "Cars", ReleaseDate = new DateTime(2006, 6, 8), Genre = "Adventure" },
                new Movie { ID = 36557, Title = "Casino Royale", ReleaseDate = new DateTime(2006, 11, 14), Genre = "Adventure" },
                new Movie { ID = 198184, Title = "Chappie", ReleaseDate = new DateTime(2015, 3, 4), Genre = "Action" },
                new Movie { ID = 76726, Title = "Chronicle", ReleaseDate = new DateTime(2012, 2, 1), Genre = "Drama" },
                new Movie { ID = 18823, Title = "Clash of the Titans", ReleaseDate = new DateTime(2010, 4, 1), Genre = "Adventure" },
                new Movie { ID = 354912, Title = "Coco", ReleaseDate = new DateTime(2017, 10, 27), Genre = "Animation" },
                new Movie { ID = 339967, Title = "Colossal", ReleaseDate = new DateTime(2016, 6, 30), Genre = "Fantasy" },
                new Movie { ID = 37430, Title = "Conan the Barbarian", ReleaseDate = new DateTime(2011, 8, 17), Genre = "Adventure" },
                new Movie { ID = 39538, Title = "Contagion", ReleaseDate = new DateTime(2011, 9, 8), Genre = "Drama" },
                new Movie { ID = 14836, Title = "Coraline", ReleaseDate = new DateTime(2009, 2, 5), Genre = "Animation" },
                new Movie { ID = 49849, Title = "Cowboys & Aliens", ReleaseDate = new DateTime(2011, 7, 29), Genre = "Action" },
                new Movie { ID = 312221, Title = "Creed", ReleaseDate = new DateTime(2015, 11, 25), Genre = "Drama" },
                new Movie { ID = 201085, Title = "Crimson Peak", ReleaseDate = new DateTime(2015, 10, 13), Genre = "Fantasy" },
                new Movie { ID = 146, Title = "Crouching Tiger, Hidden Dragon", ReleaseDate = new DateTime(2000, 7, 6), Genre = "Adventure" },
                new Movie { ID = 419680, Title = "Daddy's Home 2", ReleaseDate = new DateTime(2017, 11, 9), Genre = "Comedy" },
                new Movie { ID = 152532, Title = "Dallas Buyers Club", ReleaseDate = new DateTime(2013, 11, 17), Genre = "Drama" },
                new Movie { ID = 62213, Title = "Dark Shadows", ReleaseDate = new DateTime(2012, 5, 8), Genre = "Fantasy" },
                new Movie { ID = 399404, Title = "Darkest Hour", ReleaseDate = new DateTime(2017, 11, 22), Genre = "Drama" },
                new Movie { ID = 293660, Title = "Deadpool", ReleaseDate = new DateTime(2016, 2, 9), Genre = "Adventure" },
                new Movie { ID = 395990, Title = "Death Wish", ReleaseDate = new DateTime(2018, 3, 2), Genre = "Drama" },
                new Movie { ID = 296524, Title = "Deepwater Horizon", ReleaseDate = new DateTime(2016, 9, 29), Genre = "Drama" },
                new Movie { ID = 184346, Title = "Deliver Us from Evil", ReleaseDate = new DateTime(2014, 7, 1), Genre = "Horror" },
                new Movie { ID = 93456, Title = "Despicable Me 2", ReleaseDate = new DateTime(2013, 6, 25), Genre = "Animation" },
                new Movie { ID = 324852, Title = "Despicable Me 3", ReleaseDate = new DateTime(2017, 6, 15), Genre = "Animation" },
                new Movie { ID = 20352, Title = "Despicable Me", ReleaseDate = new DateTime(2010, 7, 8), Genre = "Animation" },
                new Movie { ID = 127517, Title = "Disconnect", ReleaseDate = new DateTime(2012, 9, 11), Genre = "Drama" },
                new Movie { ID = 157350, Title = "Divergent", ReleaseDate = new DateTime(2014, 3, 14), Genre = "Adventure" },
                new Movie { ID = 68718, Title = "Django Unchained", ReleaseDate = new DateTime(2012, 12, 25), Genre = "Drama" },
                new Movie { ID = 284052, Title = "Doctor Strange", ReleaseDate = new DateTime(2016, 10, 25), Genre = "Adventure" },
                new Movie { ID = 301337, Title = "Downsizing", ReleaseDate = new DateTime(2017, 12, 22), Genre = "Drama" },
                new Movie { ID = 49049, Title = "Dredd", ReleaseDate = new DateTime(2012, 9, 7), Genre = "Action" },
                new Movie { ID = 11360, Title = "Dumbo", ReleaseDate = new DateTime(1941, 10, 22), Genre = "Animation" },
                new Movie { ID = 374720, Title = "Dunkirk", ReleaseDate = new DateTime(2017, 7, 19), Genre = "Drama" },
                new Movie { ID = 387592, Title = "Early Man", ReleaseDate = new DateTime(2018, 1, 26), Genre = "Adventure" },
                new Movie { ID = 137113, Title = "Edge of Tomorrow", ReleaseDate = new DateTime(2014, 5, 27), Genre = "Action" },
                new Movie { ID = 68724, Title = "Elysium", ReleaseDate = new DateTime(2013, 8, 7), Genre = "Drama" },
                new Movie { ID = 116711, Title = "Epic", ReleaseDate = new DateTime(2013, 5, 15), Genre = "Adventure" },
                new Movie { ID = 107846, Title = "Escape Plan", ReleaseDate = new DateTime(2013, 10, 9), Genre = "Action" },
                new Movie { ID = 253412, Title = "Everest", ReleaseDate = new DateTime(2015, 9, 10), Genre = "Adventure" },
                new Movie { ID = 109428, Title = "Evil Dead", ReleaseDate = new DateTime(2013, 4, 5), Genre = "Horror" },
                new Movie { ID = 264660, Title = "Ex Machina", ReleaseDate = new DateTime(2015, 1, 21), Genre = "Drama" },
                new Movie { ID = 259316, Title = "Fantastic Beasts and Where to Find Them", ReleaseDate = new DateTime(2016, 11, 16), Genre = "Adventure" },
                new Movie { ID = 166424, Title = "Fantastic Four", ReleaseDate = new DateTime(2015, 8, 5), Genre = "Adventure" },
                new Movie { ID = 82992, Title = "Fast & Furious 6", ReleaseDate = new DateTime(2013, 5, 21), Genre = "Action" },
                new Movie { ID = 51497, Title = "Fast Five", ReleaseDate = new DateTime(2011, 4, 20), Genre = "Action" },
                new Movie { ID = 364689, Title = "Ferdinand", ReleaseDate = new DateTime(2017, 12, 9), Genre = "Adventure" },
                new Movie { ID = 341174, Title = "Fifty Shades Darker", ReleaseDate = new DateTime(2017, 2, 8), Genre = "Drama" },
                new Movie { ID = 337167, Title = "Fifty Shades Freed", ReleaseDate = new DateTime(2018, 1, 17), Genre = "Drama" },
                new Movie { ID = 216015, Title = "Fifty Shades of Grey", ReleaseDate = new DateTime(2015, 2, 11), Genre = "Drama" },
                new Movie { ID = 127380, Title = "Finding Dory", ReleaseDate = new DateTime(2016, 6, 16), Genre = "Adventure" },
                new Movie { ID = 400710, Title = "Flatliners", ReleaseDate = new DateTime(2017, 9, 28), Genre = "Drama" },
                new Movie { ID = 87502, Title = "Flight", ReleaseDate = new DateTime(2012, 11, 2), Genre = "Drama" },
                new Movie { ID = 62214, Title = "Frankenweenie", ReleaseDate = new DateTime(2012, 10, 4), Genre = "Animation" },
                new Movie { ID = 26389, Title = "From Paris with Love", ReleaseDate = new DateTime(2010, 2, 5), Genre = "Action" },
                new Movie { ID = 109445, Title = "Frozen", ReleaseDate = new DateTime(2013, 11, 27), Genre = "Adventure" },
                new Movie { ID = 72559, Title = "G.I. Joe: Retaliation", ReleaseDate = new DateTime(2013, 3, 26), Genre = "Adventure" },
                new Movie { ID = 445571, Title = "Game Night", ReleaseDate = new DateTime(2018, 2, 22), Genre = "Comedy" },
                new Movie { ID = 82682, Title = "Gangster Squad", ReleaseDate = new DateTime(2013, 1, 10), Genre = "Drama" },
                new Movie { ID = 274855, Title = "Geostorm", ReleaseDate = new DateTime(2017, 10, 13), Genre = "Action" },
                new Movie { ID = 419430, Title = "Get Out", ReleaseDate = new DateTime(2017, 2, 24), Genre = "Horror" },
                new Movie { ID = 315837, Title = "Ghost in the Shell", ReleaseDate = new DateTime(2017, 3, 29), Genre = "Drama" },
                new Movie { ID = 400928, Title = "Gifted", ReleaseDate = new DateTime(2017, 4, 12), Genre = "Drama" },
                new Movie { ID = 124905, Title = "Godzilla", ReleaseDate = new DateTime(2014, 5, 14), Genre = "Drama" },
                new Movie { ID = 49047, Title = "Gravity", ReleaseDate = new DateTime(2013, 9, 27), Genre = "Drama" },
                new Movie { ID = 65291, Title = "Green Lantern: Emerald Knights", ReleaseDate = new DateTime(2011, 4, 9), Genre = "Adventure" },
                new Movie { ID = 17445, Title = "Green Lantern: First Flight", ReleaseDate = new DateTime(2009, 7, 28), Genre = "Animation" },
                new Movie { ID = 44912, Title = "Green Lantern", ReleaseDate = new DateTime(2011, 6, 16), Genre = "Adventure" },
                new Movie { ID = 283995, Title = "Guardians of the Galaxy Vol. 2", ReleaseDate = new DateTime(2017, 4, 19), Genre = "Adventure" },
                new Movie { ID = 118340, Title = "Guardians of the Galaxy", ReleaseDate = new DateTime(2014, 7, 30), Genre = "Adventure" },
                new Movie { ID = 324786, Title = "Hacksaw Ridge", ReleaseDate = new DateTime(2016, 10, 7), Genre = "Drama" },
                new Movie { ID = 440021, Title = "Happy Death Day", ReleaseDate = new DateTime(2017, 10, 12), Genre = "Horror" },
                new Movie { ID = 152601, Title = "Her", ReleaseDate = new DateTime(2013, 12, 18), Genre = "Drama" },
                new Movie { ID = 184315, Title = "Hercules", ReleaseDate = new DateTime(2014, 7, 23), Genre = "Adventure" },
                new Movie { ID = 249070, Title = "Hitman: Agent 47", ReleaseDate = new DateTime(2015, 8, 20), Genre = "Action" },
                new Movie { ID = 12222, Title = "Horton Hears a Who!", ReleaseDate = new DateTime(2008, 3, 3), Genre = "Adventure" },
                new Movie { ID = 76492, Title = "Hotel Transylvania", ReleaseDate = new DateTime(2012, 9, 20), Genre = "Fantasy" },
                new Movie { ID = 82702, Title = "How to Train Your Dragon 2", ReleaseDate = new DateTime(2014, 6, 12), Genre = "Adventure" },
                new Movie { ID = 10191, Title = "How to Train Your Dragon", ReleaseDate = new DateTime(2010, 3, 5), Genre = "Adventure" },
                new Movie { ID = 44826, Title = "Hugo", ReleaseDate = new DateTime(2011, 11, 22), Genre = "Adventure" },
                new Movie { ID = 419831, Title = "I Kill Giants", ReleaseDate = new DateTime(2018, 1, 21), Genre = "Fantasy" },
                new Movie { ID = 389015, Title = "I, Tonya", ReleaseDate = new DateTime(2017, 11, 27), Genre = "Drama" },
                new Movie { ID = 57800, Title = "Ice Age: Continental Drift", ReleaseDate = new DateTime(2012, 6, 26), Genre = "Adventure" },
                new Movie { ID = 37958, Title = "Immortals", ReleaseDate = new DateTime(2011, 11, 10), Genre = "Fantasy" },
                new Movie { ID = 49530, Title = "In Time", ReleaseDate = new DateTime(2011, 10, 27), Genre = "Action" },
                new Movie { ID = 27205, Title = "Inception", ReleaseDate = new DateTime(2010, 7, 14), Genre = "Adventure" },
                new Movie { ID = 47933, Title = "Independence Day: Resurgence", ReleaseDate = new DateTime(2016, 6, 22), Genre = "Adventure" },
                new Movie { ID = 150540, Title = "Inside Out", ReleaseDate = new DateTime(2015, 6, 9), Genre = "Animation" },
                new Movie { ID = 406563, Title = "Insidious: The Last Key", ReleaseDate = new DateTime(2018, 1, 3), Genre = "Horror" },
                new Movie { ID = 157336, Title = "Interstellar", ReleaseDate = new DateTime(2014, 11, 5), Genre = "Adventure" },
                new Movie { ID = 10138, Title = "Iron Man 2", ReleaseDate = new DateTime(2010, 4, 28), Genre = "Adventure" },
                new Movie { ID = 68721, Title = "Iron Man 3", ReleaseDate = new DateTime(2013, 4, 18), Genre = "Adventure" },
                new Movie { ID = 418078, Title = "It Comes at Night", ReleaseDate = new DateTime(2017, 6, 9), Genre = "Drama" },
                new Movie { ID = 346364, Title = "It", ReleaseDate = new DateTime(2017, 9, 6), Genre = "Drama" },
                new Movie { ID = 343611, Title = "Jack Reacher: Never Go Back", ReleaseDate = new DateTime(2016, 10, 19), Genre = "Adventure" },
                new Movie { ID = 75780, Title = "Jack Reacher", ReleaseDate = new DateTime(2012, 12, 20), Genre = "Drama" },
                new Movie { ID = 137094, Title = "Jack Ryan: Shadow Recruit", ReleaseDate = new DateTime(2014, 1, 15), Genre = "Drama" },
                new Movie { ID = 81005, Title = "Jack the Giant Slayer", ReleaseDate = new DateTime(2013, 2, 27), Genre = "Adventure" },
                new Movie { ID = 324668, Title = "Jason Bourne", ReleaseDate = new DateTime(2016, 7, 27), Genre = "Action" },
                new Movie { ID = 49529, Title = "John Carter", ReleaseDate = new DateTime(2012, 3, 7), Genre = "Adventure" },
                new Movie { ID = 324552, Title = "John Wick: Chapter 2", ReleaseDate = new DateTime(2017, 2, 8), Genre = "Action" },
                new Movie { ID = 245891, Title = "John Wick", ReleaseDate = new DateTime(2014, 10, 22), Genre = "Action" },
                new Movie { ID = 353486, Title = "Jumanji: Welcome to the Jungle", ReleaseDate = new DateTime(2017, 12, 9), Genre = "Adventure" },
                new Movie { ID = 76757, Title = "Jupiter Ascending", ReleaseDate = new DateTime(2015, 2, 4), Genre = "Adventure" },
                new Movie { ID = 323027, Title = "Justice League: Gods and Monsters", ReleaseDate = new DateTime(2015, 7, 28), Genre = "Fantasy" },
                new Movie { ID = 183011, Title = "Justice League: The Flashpoint Paradox", ReleaseDate = new DateTime(2013, 7, 28), Genre = "Adventure" },
                new Movie { ID = 297556, Title = "Justice League: Throne of Atlantis", ReleaseDate = new DateTime(2015, 1, 27), Genre = "Adventure" },
                new Movie { ID = 217993, Title = "Justice League: War", ReleaseDate = new DateTime(2014, 2, 2), Genre = "Animation" },
                new Movie { ID = 141052, Title = "Justice League", ReleaseDate = new DateTime(2017, 11, 15), Genre = "Adventure" },
                new Movie { ID = 59859, Title = "Kick-Ass 2", ReleaseDate = new DateTime(2013, 7, 17), Genre = "Adventure" },
                new Movie { ID = 23483, Title = "Kick-Ass", ReleaseDate = new DateTime(2010, 3, 22), Genre = "Action" },
                new Movie { ID = 274857, Title = "King Arthur: Legend of the Sword", ReleaseDate = new DateTime(2017, 5, 10), Genre = "Fantasy" },
                new Movie { ID = 343668, Title = "Kingsman: The Golden Circle", ReleaseDate = new DateTime(2017, 9, 20), Genre = "Adventure" },
                new Movie { ID = 207703, Title = "Kingsman: The Secret Service", ReleaseDate = new DateTime(2015, 1, 24), Genre = "Adventure" },
                new Movie { ID = 293167, Title = "Kong: Skull Island", ReleaseDate = new DateTime(2017, 3, 8), Genre = "Adventure" },
                new Movie { ID = 313297, Title = "Kubo and the Two Strings", ReleaseDate = new DateTime(2016, 8, 18), Genre = "Adventure" },
                new Movie { ID = 49444, Title = "Kung Fu Panda 2", ReleaseDate = new DateTime(2011, 5, 25), Genre = "Animation" },
                new Movie { ID = 313369, Title = "La La Land", ReleaseDate = new DateTime(2016, 11, 29), Genre = "Drama" },
                new Movie { ID = 48750, Title = "Les Miserables", ReleaseDate = new DateTime(1995, 3, 22), Genre = "Drama" },
                new Movie { ID = 87827, Title = "Life of Pi", ReleaseDate = new DateTime(2012, 11, 20), Genre = "Adventure" },
                new Movie { ID = 395992, Title = "Life", ReleaseDate = new DateTime(2017, 3, 22), Genre = "Drama" },
                new Movie { ID = 72976, Title = "Lincoln", ReleaseDate = new DateTime(2012, 11, 9), Genre = "Drama" },
                new Movie { ID = 81796, Title = "Lockout", ReleaseDate = new DateTime(2012, 4, 12), Genre = "Action" },
                new Movie { ID = 399170, Title = "Logan Lucky", ReleaseDate = new DateTime(2017, 8, 17), Genre = "Drama" },
                new Movie { ID = 263115, Title = "Logan", ReleaseDate = new DateTime(2017, 2, 28), Genre = "Drama" },
                new Movie { ID = 267860, Title = "London Has Fallen", ReleaseDate = new DateTime(2016, 3, 2), Genre = "Action" },
                new Movie { ID = 59967, Title = "Looper", ReleaseDate = new DateTime(2012, 9, 26), Genre = "Action" },
                new Movie { ID = 240832, Title = "Lucy", ReleaseDate = new DateTime(2014, 7, 25), Genre = "Action" },
                new Movie { ID = 76341, Title = "Mad Max: Fury Road", ReleaseDate = new DateTime(2015, 5, 13), Genre = "Adventure" },
                new Movie { ID = 80321, Title = "Madagascar 3: Europe's Most Wanted", ReleaseDate = new DateTime(2012, 6, 6), Genre = "Animation" },
                new Movie { ID = 102651, Title = "Maleficent", ReleaseDate = new DateTime(2014, 5, 28), Genre = "Adventure" },
                new Movie { ID = 132232, Title = "Mama", ReleaseDate = new DateTime(2013, 1, 17), Genre = "Horror" },
                new Movie { ID = 49521, Title = "Man of Steel", ReleaseDate = new DateTime(2013, 6, 12), Genre = "Adventure" },
                new Movie { ID = 399366, Title = "Marrowbone", ReleaseDate = new DateTime(2017, 10, 27), Genre = "Drama" },
                new Movie { ID = 407439, Title = "Mary Magdalene", ReleaseDate = new DateTime(2018, 3, 15), Genre = "Drama" },
                new Movie { ID = 336843, Title = "Maze Runner: The Death Cure", ReleaseDate = new DateTime(2018, 1, 10), Genre = "Adventure" },
                new Movie { ID = 41154, Title = "Men in Black 3", ReleaseDate = new DateTime(2012, 5, 23), Genre = "Action" },
                new Movie { ID = 283366, Title = "Miss Peregrine's Home for Peculiar Children", ReleaseDate = new DateTime(2016, 9, 28), Genre = "Adventure" },
                new Movie { ID = 62211, Title = "Monsters University", ReleaseDate = new DateTime(2013, 6, 20), Genre = "Animation" },
                new Movie { ID = 585, Title = "Monsters, Inc.", ReleaseDate = new DateTime(2001, 11, 1), Genre = "Animation" },
                new Movie { ID = 376867, Title = "Moonlight", ReleaseDate = new DateTime(2016, 10, 21), Genre = "Drama" },
                new Movie { ID = 27265, Title = "Mother", ReleaseDate = new DateTime(1996, 12, 25), Genre = "Comedy" },
                new Movie { ID = 392044, Title = "Murder on the Orient Express", ReleaseDate = new DateTime(2017, 11, 3), Genre = "Drama" },
                new Movie { ID = 136797, Title = "Need for Speed", ReleaseDate = new DateTime(2014, 3, 13), Genre = "Drama" },
                new Movie { ID = 195589, Title = "Neighbors", ReleaseDate = new DateTime(2014, 5, 8), Genre = "Comedy" },
                new Movie { ID = 86834, Title = "Noah", ReleaseDate = new DateTime(2014, 3, 20), Genre = "Adventure" },
                new Movie { ID = 225574, Title = "Non-Stop", ReleaseDate = new DateTime(2014, 2, 26), Genre = "Action" },
                new Movie { ID = 75656, Title = "Now You See Me", ReleaseDate = new DateTime(2013, 5, 29), Genre = "Thriller" },
                new Movie { ID = 75612, Title = "Oblivion", ReleaseDate = new DateTime(2013, 4, 10), Genre = "Adventure" },
                new Movie { ID = 157547, Title = "Oculus", ReleaseDate = new DateTime(2013, 9, 8), Genre = "Horror" },
                new Movie { ID = 179826, Title = "Odd Thomas", ReleaseDate = new DateTime(2013, 4, 16), Genre = "Thriller" },
                new Movie { ID = 117263, Title = "Olympus Has Fallen", ReleaseDate = new DateTime(2013, 3, 20), Genre = "Action" },
                new Movie { ID = 395991, Title = "Only the Brave", ReleaseDate = new DateTime(2017, 9, 22), Genre = "Drama" },
                new Movie { ID = 242512, Title = "Ouija", ReleaseDate = new DateTime(2014, 10, 24), Genre = "Horror" },
                new Movie { ID = 68726, Title = "Pacific Rim", ReleaseDate = new DateTime(2013, 7, 11), Genre = "Adventure" },
                new Movie { ID = 346648, Title = "Paddington 2", ReleaseDate = new DateTime(2017, 11, 9), Genre = "Adventure" },
                new Movie { ID = 286565, Title = "Paper Towns", ReleaseDate = new DateTime(2015, 6, 18), Genre = "Drama" },
                new Movie { ID = 119283, Title = "Parker", ReleaseDate = new DateTime(2013, 1, 23), Genre = "Action" },
                new Movie { ID = 274870, Title = "Passengers", ReleaseDate = new DateTime(2016, 12, 21), Genre = "Drama" },
                new Movie { ID = 388399, Title = "Patriots Day", ReleaseDate = new DateTime(2016, 12, 12), Genre = "Drama" },
                new Movie { ID = 76285, Title = "Percy Jackson: Sea of Monsters", ReleaseDate = new DateTime(2013, 8, 7), Genre = "Adventure" },
                new Movie { ID = 32657, Title = "Percy Jackson & the Olympians: The Lightning Thief", ReleaseDate = new DateTime(2010, 2, 1), Genre = "Adventure" },
                new Movie { ID = 285, Title = "Pirates of the Caribbean: At World's End", ReleaseDate = new DateTime(2007, 5, 19), Genre = "Adventure" },
                new Movie { ID = 58, Title = "Pirates of the Caribbean: Dead Man's Chest", ReleaseDate = new DateTime(2006, 6, 20), Genre = "Adventure" },
                new Movie { ID = 166426, Title = "Pirates of the Caribbean: Dead Men Tell No Tales", ReleaseDate = new DateTime(2017, 5, 23), Genre = "Adventure" },
                new Movie { ID = 1865, Title = "Pirates of the Caribbean: On Stranger Tides", ReleaseDate = new DateTime(2011, 5, 14), Genre = "Adventure" },
                new Movie { ID = 22, Title = "Pirates of the Caribbean: The Curse of the Black Pearl", ReleaseDate = new DateTime(2003, 7, 9), Genre = "Adventure" },
                new Movie { ID = 16866, Title = "Planet 51", ReleaseDate = new DateTime(2009, 11, 19), Genre = "Adventure" },
                new Movie { ID = 869, Title = "Planet of the Apes", ReleaseDate = new DateTime(2001, 7, 25), Genre = "Adventure" },
                new Movie { ID = 76649, Title = "Pompeii", ReleaseDate = new DateTime(2014, 2, 18), Genre = "Adventure" },
                new Movie { ID = 206487, Title = "Predestination", ReleaseDate = new DateTime(2014, 8, 28), Genre = "Thriller" },
                new Movie { ID = 9543, Title = "Prince of Persia: The Sands of Time", ReleaseDate = new DateTime(2010, 5, 19), Genre = "Adventure" },
                new Movie { ID = 70981, Title = "Prometheus", ReleaseDate = new DateTime(2012, 5, 30), Genre = "Adventure" },
                new Movie { ID = 417859, Title = "Puss in Boots", ReleaseDate = new DateTime(2011, 10, 28), Genre = "Adventure" },
                new Movie { ID = 427641, Title = "Rampage", ReleaseDate = new DateTime(2018, 4, 12), Genre = "Adventure" },
                new Movie { ID = 2062, Title = "Ratatouille", ReleaseDate = new DateTime(2007, 6, 22), Genre = "Fantasy" },
                new Movie { ID = 333339, Title = "Ready Player One", ReleaseDate = new DateTime(2018, 3, 28), Genre = "Adventure" },
                new Movie { ID = 146216, Title = "RED 2", ReleaseDate = new DateTime(2013, 7, 18), Genre = "Action" },
                new Movie { ID = 49730, Title = "Red Riding Hood", ReleaseDate = new DateTime(2011, 3, 11), Genre = "Fantasy" },
                new Movie { ID = 401981, Title = "Red Sparrow", ReleaseDate = new DateTime(2018, 2, 28), Genre = "Thriller" },
                new Movie { ID = 39514, Title = "RED", ReleaseDate = new DateTime(2010, 10, 13), Genre = "Adventure" },
                new Movie { ID = 71679, Title = "Resident Evil: Retribution", ReleaseDate = new DateTime(2012, 9, 12), Genre = "Horror" },
                new Movie { ID = 173897, Title = "Resident Evil: The Final Chapter", ReleaseDate = new DateTime(2016, 12, 23), Genre = "Horror" },
                new Movie { ID = 87421, Title = "Riddick", ReleaseDate = new DateTime(2013, 9, 2), Genre = "Action" },
                new Movie { ID = 46195, Title = "Rio", ReleaseDate = new DateTime(2011, 4, 3), Genre = "Adventure" },
                new Movie { ID = 81188, Title = "Rise of the Guardians", ReleaseDate = new DateTime(2012, 11, 21), Genre = "Fantasy" },
                new Movie { ID = 294993, Title = "Rise of the Legend", ReleaseDate = new DateTime(2014, 11, 20), Genre = "Drama" },
                new Movie { ID = 61791, Title = "Rise of the Planet of the Apes", ReleaseDate = new DateTime(2011, 8, 3), Genre = "Drama" },
                new Movie { ID = 5548, Title = "RoboCop", ReleaseDate = new DateTime(1987, 7, 17), Genre = "Action" },
                new Movie { ID = 9928, Title = "Robots", ReleaseDate = new DateTime(2005, 3, 10), Genre = "Animation" },
                new Movie { ID = 80585, Title = "Rock of Ages", ReleaseDate = new DateTime(2012, 6, 13), Genre = "Drama" },
                new Movie { ID = 221731, Title = "Rurouni Kenshin: Kyoto Inferno", ReleaseDate = new DateTime(2014, 8, 1), Genre = "Adventure" },
                new Movie { ID = 221732, Title = "Rurouni Kenshin: The Legend Ends", ReleaseDate = new DateTime(2014, 9, 13), Genre = "Adventure" },
                new Movie { ID = 127533, Title = "Rurouni Kenshin", ReleaseDate = new DateTime(2012, 8, 25), Genre = "Drama" },
                new Movie { ID = 27576, Title = "Salt", ReleaseDate = new DateTime(2010, 7, 21), Genre = "Action" },
                new Movie { ID = 225886, Title = "Sex Tape", ReleaseDate = new DateTime(2014, 7, 17), Genre = "Comedy" },
                new Movie { ID = 58574, Title = "Sherlock Holmes: A Game of Shadows", ReleaseDate = new DateTime(2011, 11, 22), Genre = "Adventure" },
                new Movie { ID = 11324, Title = "Shutter Island", ReleaseDate = new DateTime(2010, 2, 14), Genre = "Drama" },
                new Movie { ID = 82693, Title = "Silver Linings Playbook", ReleaseDate = new DateTime(2012, 9, 8), Genre = "Drama" },
                new Movie { ID = 82507, Title = "Sinister", ReleaseDate = new DateTime(2012, 3, 29), Genre = "Horror" },
                new Movie { ID = 37724, Title = "Skyfall", ReleaseDate = new DateTime(2012, 10, 25), Genre = "Adventure" },
                new Movie { ID = 110415, Title = "Snowpiercer", ReleaseDate = new DateTime(2013, 8, 1), Genre = "Drama" },
                new Movie { ID = 251519, Title = "Son of Batman", ReleaseDate = new DateTime(2014, 4, 20), Genre = "Adventure" },
                new Movie { ID = 235260, Title = "Son of God", ReleaseDate = new DateTime(2014, 2, 28), Genre = "Drama" },
                new Movie { ID = 315635, Title = "Spider-Man: Homecoming", ReleaseDate = new DateTime(2017, 7, 5), Genre = "Adventure" },
                new Movie { ID = 129, Title = "Spirited Away", ReleaseDate = new DateTime(2001, 7, 20), Genre = "Fantasy" },
                new Movie { ID = 381288, Title = "Split", ReleaseDate = new DateTime(2017, 1, 19), Genre = "Horror" },
                new Movie { ID = 54138, Title = "Star Trek Into Darkness", ReleaseDate = new DateTime(2013, 5, 5), Genre = "Adventure" },
                new Movie { ID = 13475, Title = "Star Trek", ReleaseDate = new DateTime(2009, 5, 6), Genre = "Adventure" },
                new Movie { ID = 140607, Title = "Star Wars: The Force Awakens", ReleaseDate = new DateTime(2015, 12, 15), Genre = "Adventure" },
                new Movie { ID = 181808, Title = "Star Wars: The Last Jedi", ReleaseDate = new DateTime(2017, 12, 13), Genre = "Adventure" },
                new Movie { ID = 297761, Title = "Suicide Squad", ReleaseDate = new DateTime(2016, 8, 2), Genre = "Adventure" },
                new Movie { ID = 37686, Title = "Super 8", ReleaseDate = new DateTime(2011, 6, 8), Genre = "Thriller" },
                new Movie { ID = 1452, Title = "Superman Returns", ReleaseDate = new DateTime(2006, 6, 28), Genre = "Adventure" },
                new Movie { ID = 19959, Title = "Surrogates", ReleaseDate = new DateTime(2009, 9, 24), Genre = "Action" },
                new Movie { ID = 38757, Title = "Tangled", ReleaseDate = new DateTime(2010, 2, 3), Genre = "Animation" },
                new Movie { ID = 72105, Title = "Ted", ReleaseDate = new DateTime(2012, 6, 29), Genre = "Fantasy" },
                new Movie { ID = 408647, Title = "Teen Titans: The Judas Contract", ReleaseDate = new DateTime(2017, 3, 22), Genre = "Animation" },
                new Movie { ID = 102382, Title = "The Amazing Spider-Man 2", ReleaseDate = new DateTime(2014, 4, 16), Genre = "Adventure" },
                new Movie { ID = 1930, Title = "The Amazing Spider-Man", ReleaseDate = new DateTime(2012, 6, 27), Genre = "Adventure" },
                new Movie { ID = 209247, Title = "The Art of the Steal", ReleaseDate = new DateTime(2013, 9, 11), Genre = "Comedy" },
                new Movie { ID = 4512, Title = "The Assassination of Jesse James by the Coward Robert Ford", ReleaseDate = new DateTime(2007, 9, 2), Genre = "Drama" },
                new Movie { ID = 24428, Title = "The Avengers", ReleaseDate = new DateTime(2012, 4, 25), Genre = "Adventure" },
                new Movie { ID = 341006, Title = "The Belko Experiment", ReleaseDate = new DateTime(2016, 3, 17), Genre = "Action" },
                new Movie { ID = 295693, Title = "The Boss Baby", ReleaseDate = new DateTime(2017, 3, 23), Genre = "Animation" },
                new Movie { ID = 2501, Title = "The Bourne Identity", ReleaseDate = new DateTime(2002, 6, 14), Genre = "Drama" },
                new Movie { ID = 49040, Title = "The Bourne Legacy", ReleaseDate = new DateTime(2012, 8, 8), Genre = "Action" },
                new Movie { ID = 2502, Title = "The Bourne Supremacy", ReleaseDate = new DateTime(2004, 7, 23), Genre = "Drama" },
                new Movie { ID = 2503, Title = "The Bourne Ultimatum", ReleaseDate = new DateTime(2007, 8, 3), Genre = "Drama" },
                new Movie { ID = 22970, Title = "The Cabin in the Woods", ReleaseDate = new DateTime(2012, 4, 12), Genre = "Horror" },
                new Movie { ID = 77953, Title = "The Campaign", ReleaseDate = new DateTime(2012, 8, 9), Genre = "Comedy" },
                new Movie { ID = 2454, Title = "The Chronicles of Narnia: Prince Caspian", ReleaseDate = new DateTime(2008, 5, 15), Genre = "Adventure" },
                new Movie { ID = 10140, Title = "The Chronicles of Narnia: The Voyage of the Dawn Treader", ReleaseDate = new DateTime(2010, 8, 13), Genre = "Adventure" },
                new Movie { ID = 399035, Title = "The Commuter", ReleaseDate = new DateTime(2018, 1, 11), Genre = "Drama" },
                new Movie { ID = 259693, Title = "The Conjuring 2", ReleaseDate = new DateTime(2016, 5, 13), Genre = "Horror" },
                new Movie { ID = 138843, Title = "The Conjuring", ReleaseDate = new DateTime(2013, 7, 18), Genre = "Horror" },
                new Movie { ID = 11362, Title = "The Count of Monte Cristo", ReleaseDate = new DateTime(2002, 1, 23), Genre = "Adventure" },
                new Movie { ID = 49519, Title = "The Croods", ReleaseDate = new DateTime(2013, 3, 20), Genre = "Adventure" },
                new Movie { ID = 306819, Title = "The Danish Girl", ReleaseDate = new DateTime(2015, 11, 27), Genre = "Drama" },
                new Movie { ID = 49026, Title = "The Dark Knight Rises", ReleaseDate = new DateTime(2012, 7, 16), Genre = "Drama" },
                new Movie { ID = 155, Title = "The Dark Knight", ReleaseDate = new DateTime(2008, 7, 16), Genre = "Drama" },
                new Movie { ID = 353491, Title = "The Dark Tower", ReleaseDate = new DateTime(2017, 8, 3), Genre = "Fantasy" },
                new Movie { ID = 487670, Title = "The Death of Superman", ReleaseDate = new DateTime(2018, 7, 3), Genre = "Animation" },
                new Movie { ID = 76493, Title = "The Dictator", ReleaseDate = new DateTime(2012, 5, 15), Genre = "Comedy" },
                new Movie { ID = 371638, Title = "The Disaster Artist", ReleaseDate = new DateTime(2017, 3, 12), Genre = "Drama" },
                new Movie { ID = 222935, Title = "The Fault in Our Stars", ReleaseDate = new DateTime(2014, 5, 16), Genre = "Drama" },
                new Movie { ID = 379149, Title = "The Foreigner", ReleaseDate = new DateTime(2017, 9, 28), Genre = "Drama" },
                new Movie { ID = 64682, Title = "The Great Gatsby", ReleaseDate = new DateTime(2013, 5, 10), Genre = "Drama" },
                new Movie { ID = 311324, Title = "The Great Wall", ReleaseDate = new DateTime(2016, 12, 16), Genre = "Adventure" },
                new Movie { ID = 316029, Title = "The Greatest Showman", ReleaseDate = new DateTime(2017, 12, 20), Genre = "Drama" },
                new Movie { ID = 40805, Title = "The Green Hornet", ReleaseDate = new DateTime(2011, 1, 12), Genre = "Action" },
                new Movie { ID = 390043, Title = "The Hitman's Bodyguard", ReleaseDate = new DateTime(2017, 8, 16), Genre = "Action" },
                new Movie { ID = 122917, Title = "The Hobbit: The Battle of the Five Armies", ReleaseDate = new DateTime(2014, 12, 10), Genre = "Adventure" },
                new Movie { ID = 57158, Title = "The Hobbit: The Desolation of Smaug", ReleaseDate = new DateTime(2013, 12, 11), Genre = "Adventure" },
                new Movie { ID = 101299, Title = "The Hunger Games: Catching Fire", ReleaseDate = new DateTime(2013, 11, 15), Genre = "Adventure" },
                new Movie { ID = 70160, Title = "The Hunger Games", ReleaseDate = new DateTime(2012, 3, 12), Genre = "Adventure" },
                new Movie { ID = 430040, Title = "The Hurricane Heist", ReleaseDate = new DateTime(2018, 2, 1), Genre = "Action" },
                new Movie { ID = 80278, Title = "The Impossible", ReleaseDate = new DateTime(2012, 9, 9), Genre = "Drama" },
                new Movie { ID = 124459, Title = "The Incredible Burt Wonderstone", ReleaseDate = new DateTime(2013, 3, 14), Genre = "Comedy" },
                new Movie { ID = 1724, Title = "The Incredible Hulk", ReleaseDate = new DateTime(2008, 6, 12), Genre = "Adventure" },
                new Movie { ID = 9806, Title = "The Incredibles", ReleaseDate = new DateTime(2004, 11, 5), Genre = "Adventure" },
                new Movie { ID = 278927, Title = "The Jungle Book", ReleaseDate = new DateTime(2016, 4, 7), Genre = "Adventure" },
                new Movie { ID = 156700, Title = "The Kings of Summer", ReleaseDate = new DateTime(2013, 1, 19), Genre = "Drama" },
                new Movie { ID = 10196, Title = "The Last Airbender", ReleaseDate = new DateTime(2010, 6, 30), Genre = "Adventure" },
                new Movie { ID = 76640, Title = "The Last Stand", ReleaseDate = new DateTime(2013, 1, 12), Genre = "Action" },
                new Movie { ID = 324849, Title = "The Lego Batman Movie", ReleaseDate = new DateTime(2017, 2, 8), Genre = "Fantasy" },
                new Movie { ID = 333484, Title = "The Magnificent Seven", ReleaseDate = new DateTime(2016, 9, 14), Genre = "Adventure" },
                new Movie { ID = 450322, Title = "The Man Who Invented Christmas", ReleaseDate = new DateTime(2017, 10, 12), Genre = "Drama" },
                new Movie { ID = 286217, Title = "The Martian", ReleaseDate = new DateTime(2015, 9, 30), Genre = "Adventure" },
                new Movie { ID = 604, Title = "The Matrix Reloaded", ReleaseDate = new DateTime(2003, 5, 15), Genre = "Adventure" },
                new Movie { ID = 605, Title = "The Matrix Revolutions", ReleaseDate = new DateTime(2003, 11, 5), Genre = "Adventure" },
                new Movie { ID = 603, Title = "The Matrix", ReleaseDate = new DateTime(1999, 3, 30), Genre = "Action" },
                new Movie { ID = 198663, Title = "The Maze Runner", ReleaseDate = new DateTime(2014, 9, 10), Genre = "Action" },
                new Movie { ID = 152760, Title = "The Monuments Men", ReleaseDate = new DateTime(2014, 1, 24), Genre = "Drama" },
                new Movie { ID = 64328, Title = "The Muppets", ReleaseDate = new DateTime(2011, 11, 22), Genre = "Comedy" },
                new Movie { ID = 9479, Title = "The Nightmare Before Christmas", ReleaseDate = new DateTime(1993, 10, 9), Genre = "Fantasy" },
                new Movie { ID = 412950, Title = "The Orphanage", ReleaseDate = new DateTime(2016, 8, 26), Genre = "Horror" },
                new Movie { ID = 193610, Title = "The Other Woman", ReleaseDate = new DateTime(2014, 4, 16), Genre = "Comedy" },
                new Movie { ID = 97367, Title = "The Place Beyond the Pines", ReleaseDate = new DateTime(2013, 3, 20), Genre = "Drama" },
                new Movie { ID = 446354, Title = "The Post", ReleaseDate = new DateTime(2018, 1, 11), Genre = "Drama" },
                new Movie { ID = 316727, Title = "The Purge: Election Year", ReleaseDate = new DateTime(2016, 6, 29), Genre = "Horror" },
                new Movie { ID = 70436, Title = "The Raven", ReleaseDate = new DateTime(2012, 3, 9), Genre = "Thriller" },
                new Movie { ID = 281957, Title = "The Revenant", ReleaseDate = new DateTime(2015, 12, 25), Genre = "Adventure" },
                new Movie { ID = 116745, Title = "The Secret Life of Walter Mitty", ReleaseDate = new DateTime(2013, 12, 18), Genre = "Adventure" },
                new Movie { ID = 399055, Title = "The Shape of Water", ReleaseDate = new DateTime(2017, 12, 1), Genre = "Fantasy" },
                new Movie { ID = 694, Title = "The Shining", ReleaseDate = new DateTime(1980, 5, 22), Genre = "Horror" },
                new Movie { ID = 27022, Title = "The Sorcerer's Apprentice", ReleaseDate = new DateTime(2010, 7, 13), Genre = "Adventure" },
                new Movie { ID = 15121, Title = "The Sound of Music", ReleaseDate = new DateTime(1965, 3, 2), Genre = "Drama" },
                new Movie { ID = 365942, Title = "The Space Between Us", ReleaseDate = new DateTime(2017, 1, 26), Genre = "Adventure" },
                new Movie { ID = 476926, Title = "The Titan", ReleaseDate = new DateTime(2018, 3, 30), Genre = "Thriller" },
                new Movie { ID = 293670, Title = "The Wailing", ReleaseDate = new DateTime(2016, 5, 12), Genre = "Horror" },
                new Movie { ID = 310131, Title = "The Witch", ReleaseDate = new DateTime(2016, 2, 19), Genre = "Horror" },
                new Movie { ID = 106646, Title = "The Wolf of Wall Street", ReleaseDate = new DateTime(2013, 12, 25), Genre = "Drama" },
                new Movie { ID = 288158, Title = "The Woman in Black 2: Angel of Death", ReleaseDate = new DateTime(2014, 12, 30), Genre = "Drama" },
                new Movie { ID = 76338, Title = "Thor: The Dark World", ReleaseDate = new DateTime(2013, 10, 29), Genre = "Adventure" },
                new Movie { ID = 10195, Title = "Thor", ReleaseDate = new DateTime(2011, 4, 21), Genre = "Adventure" },
                new Movie { ID = 13179, Title = "Tinker Bell", ReleaseDate = new DateTime(2008, 10, 27), Genre = "Adventure" },
                new Movie { ID = 1273, Title = "TMNT", ReleaseDate = new DateTime(2007, 3, 23), Genre = "Adventure" },
                new Movie { ID = 338970, Title = "Tomb Raider", ReleaseDate = new DateTime(2018, 3, 5), Genre = "Adventure" },
                new Movie { ID = 861, Title = "Total Recall", ReleaseDate = new DateTime(1990, 6, 1), Genre = "Adventure" },
                new Movie { ID = 473149, Title = "Traffik", ReleaseDate = new DateTime(2018, 4, 20), Genre = "Horror" },
                new Movie { ID = 396535, Title = "Train to Busan", ReleaseDate = new DateTime(2016, 7, 20), Genre = "Horror" },
                new Movie { ID = 91314, Title = "Transformers: Age of Extinction", ReleaseDate = new DateTime(2014, 6, 25), Genre = "Adventure" },
                new Movie { ID = 38356, Title = "Transformers: Dark of the Moon", ReleaseDate = new DateTime(2011, 6, 28), Genre = "Adventure" },
                new Movie { ID = 8373, Title = "Transformers: Revenge of the Fallen", ReleaseDate = new DateTime(2009, 6, 19), Genre = "Adventure" },
                new Movie { ID = 335988, Title = "Transformers: The Last Knight", ReleaseDate = new DateTime(2017, 6, 16), Genre = "Adventure" },
                new Movie { ID = 1858, Title = "Transformers", ReleaseDate = new DateTime(2007, 6, 27), Genre = "Adventure" },
                new Movie { ID = 20526, Title = "TRON: Legacy", ReleaseDate = new DateTime(2010, 12, 10), Genre = "Adventure" },
                new Movie { ID = 460019, Title = "Truth or Dare", ReleaseDate = new DateTime(2018, 4, 12), Genre = "Horror" },
                new Movie { ID = 257785, Title = "Tulip Fever", ReleaseDate = new DateTime(2017, 7, 13), Genre = "Drama" },
                new Movie { ID = 9741, Title = "Unbreakable", ReleaseDate = new DateTime(2000, 11, 13), Genre = "Drama" },
                new Movie { ID = 346672, Title = "Underworld: Blood Wars", ReleaseDate = new DateTime(2016, 11, 28), Genre = "Fantasy" },
                new Movie { ID = 834, Title = "Underworld: Evolution", ReleaseDate = new DateTime(2006, 1, 12), Genre = "Fantasy" },
                new Movie { ID = 12437, Title = "Underworld: Rise of the Lycans", ReleaseDate = new DateTime(2009, 1, 22), Genre = "Adventure" },
                new Movie { ID = 277, Title = "Underworld", ReleaseDate = new DateTime(2003, 9, 19), Genre = "Fantasy" },
                new Movie { ID = 467660, Title = "Unsane", ReleaseDate = new DateTime(2018, 3, 22), Genre = "Horror" },
                new Movie { ID = 44048, Title = "Unstoppable", ReleaseDate = new DateTime(2010, 11, 4), Genre = "Action" },
                new Movie { ID = 58244, Title = "Upside Down", ReleaseDate = new DateTime(2012, 9, 27), Genre = "Fantasy" },
                new Movie { ID = 752, Title = "V for Vendetta", ReleaseDate = new DateTime(2006, 3, 15), Genre = "Fantasy" },
                new Movie { ID = 339964, Title = "Valerian and the City of a Thousand Planets", ReleaseDate = new DateTime(2017, 7, 20), Genre = "Adventure" },
                new Movie { ID = 228066, Title = "Victor Frankenstein", ReleaseDate = new DateTime(2015, 11, 10), Genre = "Drama" },
                new Movie { ID = 423899, Title = "Victoria & Abdul", ReleaseDate = new DateTime(2017, 9, 14), Genre = "Drama" },
                new Movie { ID = 301372, Title = "Voice from the Stone", ReleaseDate = new DateTime(2017, 4, 28), Genre = "Drama" },
                new Movie { ID = 281338, Title = "War for the Planet of the Apes", ReleaseDate = new DateTime(2017, 7, 11), Genre = "Drama" },
                new Movie { ID = 82654, Title = "Warm Bodies", ReleaseDate = new DateTime(2013, 1, 31), Genre = "Horror" },
                new Movie { ID = 406990, Title = "What Happened to Monday", ReleaseDate = new DateTime(2017, 8, 18), Genre = "Drama" },
                new Movie { ID = 117251, Title = "White House Down", ReleaseDate = new DateTime(2013, 6, 27), Genre = "Drama" },
                new Movie { ID = 416234, Title = "Winchester", ReleaseDate = new DateTime(2018, 2, 2), Genre = "Fantasy" },
                new Movie { ID = 7978, Title = "The Wolfman", ReleaseDate = new DateTime(2010, 2, 11), Genre = "Fantasy" },
                new Movie { ID = 297762, Title = "Wonder Woman", ReleaseDate = new DateTime(2017, 5, 30), Genre = "Adventure" },
                new Movie { ID = 406997, Title = "Wonder", ReleaseDate = new DateTime(2017, 11, 13), Genre = "Drama" },
                new Movie { ID = 72190, Title = "World War Z", ReleaseDate = new DateTime(2013, 6, 20), Genre = "Drama" },
                new Movie { ID = 57165, Title = "Wrath of the Titans", ReleaseDate = new DateTime(2012, 3, 27), Genre = "Adventure" },
                new Movie { ID = 82690, Title = "Wreck-It Ralph", ReleaseDate = new DateTime(2012, 11, 1), Genre = "Adventure" },
                new Movie { ID = 49538, Title = "X-Men: First Class", ReleaseDate = new DateTime(2011, 6, 1), Genre = "Adventure" },
                new Movie { ID = 398181, Title = "You Were Never Really Here", ReleaseDate = new DateTime(2017, 11, 8), Genre = "Drama" },
                new Movie { ID = 329833, Title = "Zoolander 2", ReleaseDate = new DateTime(2016, 2, 6), Genre = "Comedy" }
            );
        }
    }
}
